version: "3.8"

services:
  backend:
    image: php:8.1-apache
    container_name: backend_php
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
